/*
  Practica 2 - Jenkinsfile dummy (PUNTO DE PARTIDA)

  Este Jenkinsfile es intencionalmente simple. En la Practica 2 iras anadiendo
  piezas (stages, agents, funciones Groovy, Docker build, docker compose, etc.)
  hasta construir un pipeline CI/CD completo.
*/

pipeline {
  // `agent any` = el pipeline se ejecuta en cualquier nodo/agente disponible.
  agent any

  stages {
    stage('Test') {
      /*
        `agent` dentro de un stage permite que SOLO ese stage se ejecute en un contexto concreto.
        En este caso, usamos Docker como capa de virtualizacion: los comandos se ejecutan dentro
        de un contenedor temporal.
      */
      agent {
        docker {
          image 'python:3.6-slim' //Imagen que usará el pipeline para nuestra ejecución (en este caso un test)
        }
      }
      steps {
        sh 'python --version'
        sh 'pip install -r requirements.txt' //Instalamos todas las dependencias del proyecto. Nos interesa pytest, pero instalamos todo el requirements
        sh 'pytest -v' //Ejecutamos los test disponibles (buscará automáticamente en /test/test_capitalize.py)
      }
    }
    // Este segundo stage es para hacer build del docker, siguiendo los pasos indicados en la práctica
    //Usamos el agent del pipeline (any) y construimos el docker (esperando que sea todo correcto) e indicamos dónde está el Dockerfile (donde se indica la imagen a construir) en /devops
    //Añadimos una etiqueta (tag). e indicamos con -f donde está el Dockerfile y el contexto (.)
    stage('docker build'){
      steps{
        sh 'docker build -t contrerasadr/devops-training-2025-python-app:0.0.1 -f devops/Dockerfile .'
      }
    }
    /**
    * En este stage intentaré levantar el contenedor previamente construido. Usaré el documento docker-compose.yml 
    * Usaremos -d para evitar que se ejecute en primer plano mostrando logs en pantalla (esto no termina hasta terminar con la ejecusión del programa)
    * Una vez levantado el contenedor, comprobamos su funcionamiento: Investigamos cual será la URL de la app en app.py y hacemos un curl para comprobar que se peude acceder.
    * De los 2 puertos 0000:0000 usamos el de la izq. El de la derecha es el que escucha la app dentro del contenedor
    * Por último limpiamos vólumenes al apagar el contenedor.
    * =============================================================
    * Con --fail interrumpimos la ejecusión del pipeline y no seguimos si falla el curl
    * También podemos verificar el contenido en el curl para evaluar si es correcta la conexión o no... Pero más adelante
    * Con sleep esperamos a que se levante el contenedor con un margen que decidamos (10s en este caso)
    * Con post-always ejecutamos una acción independientemente del resultado de pasos anteriores, EJ: Si la app rompe, no se limpian los volumenes si no lo indicamos en post-always 
    * Con when le decimos que esta parte (Despliegue/CD) solo lo haga cuando se esté en la rama develop/master, más bién, cuando se suba algo nuevo a alguna de estas
    */
    stage('Despliegue docker-compose'){
      when{
        anyOf{
          branch 'develop'
          branch 'master'
        }

      }
      steps{
        sh 'docker compose up -d'
        sh 'sleep 10'
        sh 'docker compose logs app'
        sh 'curl --fail http://localhost:5001'
      }
      post {
        always {
          sh 'docker compose down --volumes'
        }
      }
    }
  }
}