/*
  Practica 2 - Jenkinsfile dummy (PUNTO DE PARTIDA)

  Este Jenkinsfile es intencionalmente simple. En la Practica 2 iras anadiendo
  piezas (stages, agents, funciones Groovy, Docker build, docker compose, etc.)
  hasta construir un pipeline CI/CD completo.
*/

pipeline {
  // `agent any` = el pipeline se ejecuta en cualquier nodo/agente disponible.
  agent any

  stages {
    stage('Test') {
      /*
        `agent` dentro de un stage permite que SOLO ese stage se ejecute en un contexto concreto.
        En este caso, usamos Docker como capa de virtualizacion: los comandos se ejecutan dentro
        de un contenedor temporal.
      */
      agent {
        docker {
          image 'python:3.6-slim' //Imagen que usará el pipeline para nuestra ejecución (en este caso un test)
        }
      }
      steps {
        sh 'python --version'
        sh 'pip install -r requirements.txt' //Instalamos todas las dependencias del proyecto. Nos interesa pytest, pero instalamos todo el requirements
        sh 'pytest -v' //Ejecutamos los test disponibles (buscará automáticamente en /test/test_capitalize.py)
      }
    }
    // Este segundo stage es para hacer build del docker, siguiendo los pasos indicados en la práctica
    //Usamos el agent del pipeline (any) y construimos el docker (esperando que sea todo correcto) en el contexto actual (.)
    //Añadimos una etiqueta (tag)
    stage('docker build'){
      steps{
        sh 'docker build -t docker-build-python:1.0.0 .'
      }
    }
  }
}